// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD2F2q_SaVX596WnzJuytz-JoMPAHLHt4',
    appId: '1:166417210103:web:f56c877d76b79b997051f2',
    messagingSenderId: '166417210103',
    projectId: 'learningfirebase-f0ef2',
    authDomain: 'learningfirebase-f0ef2.firebaseapp.com',
    storageBucket: 'learningfirebase-f0ef2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwcngr6zokTKPe7dJSmmNC1N8YTnmXO8',
    appId: '1:166417210103:android:933e8a1c0e4caaef7051f2',
    messagingSenderId: '166417210103',
    projectId: 'learningfirebase-f0ef2',
    storageBucket: 'learningfirebase-f0ef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB3iSU1NITLwIUOjrOvPt9e79wT4KbmrQ',
    appId: '1:166417210103:ios:d4f77799c814020a7051f2',
    messagingSenderId: '166417210103',
    projectId: 'learningfirebase-f0ef2',
    storageBucket: 'learningfirebase-f0ef2.appspot.com',
    iosClientId: '166417210103-ok63g5r9d2l3ail5ir6usrj8p4m3s3q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingHttps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB3iSU1NITLwIUOjrOvPt9e79wT4KbmrQ',
    appId: '1:166417210103:ios:d4f77799c814020a7051f2',
    messagingSenderId: '166417210103',
    projectId: 'learningfirebase-f0ef2',
    storageBucket: 'learningfirebase-f0ef2.appspot.com',
    iosClientId: '166417210103-ok63g5r9d2l3ail5ir6usrj8p4m3s3q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.networkingHttps',
  );
}
